### ISSUE TITLE
Does this work for both concave and convex polygons?

### ISSUE THREAD

**Issue by Qqwy** [tpoulsen/collision#15]
I just found out about this library by reading the Elixir Weekly and your blog article.

One thing I am wondering, which wasn't really clear in the blog article nor the readme: Does this library work both convex and concave polygons, or only convex ones?

(Concave polygons are polygons that have at least one point with an angle > 180 degrees)

The Separating Axis Theorem (at least in its usual form) only works when polygons are convex. [See Wikipedia for an explanation](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem).

Most libraries that use the SAT either split a concave polygon in multiple convex ones(a collision then happens when the other shape collies with any of these), or they just do not support them at all.

**Comment by tpoulsen** [comment]
Currently only convex regular polygons are implemented.

I'm intending to add general convex polygons next, then work on handling
concave polygons, methods of collision detection other than via SAT, and 3D
objects before hitting 1.0.
